/* tslint:disable */
/* eslint-disable */
/**
 * API Testing
 * Api for Testing Stuff
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface HealthLog
 */
export interface HealthLog {
    /**
     * 
     * @type {string}
     * @memberof HealthLog
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof HealthLog
     */
    'update': string;
    /**
     * 
     * @type {string}
     * @memberof HealthLog
     */
    'updateDay': string;
    /**
     * 
     * @type {string}
     * @memberof HealthLog
     */
    'created': string;
    /**
     * 
     * @type {string}
     * @memberof HealthLog
     */
    'createdDay': string;
    /**
     * 
     * @type {string}
     * @memberof HealthLog
     */
    'delete': string;
    /**
     * 
     * @type {string}
     * @memberof HealthLog
     */
    'url': string;
    /**
     * 
     * @type {number}
     * @memberof HealthLog
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof HealthLog
     */
    'checkedDate': string;
    /**
     * 
     * @type {Website}
     * @memberof HealthLog
     */
    'website': Website;
}
/**
 * 
 * @export
 * @interface Website
 */
export interface Website {
    /**
     * 
     * @type {string}
     * @memberof Website
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof Website
     */
    'update': string;
    /**
     * 
     * @type {string}
     * @memberof Website
     */
    'updateDay': string;
    /**
     * 
     * @type {string}
     * @memberof Website
     */
    'created': string;
    /**
     * 
     * @type {string}
     * @memberof Website
     */
    'createdDay': string;
    /**
     * 
     * @type {string}
     * @memberof Website
     */
    'delete': string;
    /**
     * 
     * @type {string}
     * @memberof Website
     */
    'url': string;
    /**
     * 
     * @type {boolean}
     * @memberof Website
     */
    'activeLog': boolean;
    /**
     * 
     * @type {Array<HealthLog>}
     * @memberof Website
     */
    'healthLog': Array<HealthLog>;
}
/**
 * 
 * @export
 * @interface WebsiteDto
 */
export interface WebsiteDto {
    /**
     * 
     * @type {string}
     * @memberof WebsiteDto
     */
    'url': string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {WebsiteDto} websiteDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerAddWebsite: async (websiteDto: WebsiteDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'websiteDto' is not null or undefined
            assertParamExists('appControllerAddWebsite', 'websiteDto', websiteDto)
            const localVarPath = `/create/website`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(websiteDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerCheckOnlineStatus: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/checkAllWebsites`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerLoadAllWebsites: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/load/allWebsites`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {WebsiteDto} websiteDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async appControllerAddWebsite(websiteDto: WebsiteDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appControllerAddWebsite(websiteDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.appControllerAddWebsite']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async appControllerCheckOnlineStatus(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appControllerCheckOnlineStatus(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.appControllerCheckOnlineStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async appControllerLoadAllWebsites(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Website>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appControllerLoadAllWebsites(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.appControllerLoadAllWebsites']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @param {WebsiteDto} websiteDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerAddWebsite(websiteDto: WebsiteDto, options?: any): AxiosPromise<void> {
            return localVarFp.appControllerAddWebsite(websiteDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerCheckOnlineStatus(options?: any): AxiosPromise<void> {
            return localVarFp.appControllerCheckOnlineStatus(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerLoadAllWebsites(options?: any): AxiosPromise<Array<Website>> {
            return localVarFp.appControllerLoadAllWebsites(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @param {WebsiteDto} websiteDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public appControllerAddWebsite(websiteDto: WebsiteDto, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).appControllerAddWebsite(websiteDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public appControllerCheckOnlineStatus(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).appControllerCheckOnlineStatus(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public appControllerLoadAllWebsites(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).appControllerLoadAllWebsites(options).then((request) => request(this.axios, this.basePath));
    }
}



